### ISSUE TITLE
Little issue in line 1049

### ISSUE THREAD

**Issue by carlospolop** [berzerk0/BEWGor#4]
In this line you can find: fem_syn_choice = spaceShaver(male_syn_choice)
but you probably want to change it to: fem_syn_choice = spaceShaver(fem_syn_choice)
If not, the program will exit with an error when you choose the female gender when the program asks.
I have sent you a pull request with this change

**Comment by berzerk0** [comment]
Fixed about 2 weeks ago - thanks for catching that!
